server:
  port: 8080
  servlet:
    context-path: /api/v1

app:
  file:
    store-dir: "D:/upload"
    download-prefix: http://localhost:8080/api/v1/file/download/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/imageai"
    username: root
    password: "123456"
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  redis:
    host: localhost
    port: 6379
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true

jwt:
  signer-key: "3fc35280eaa58f16073a24ca3c5f0dd2d3ecbb6f89a3f013eba40c91bb775491"
  valid-duration: 1800          # 30 phút
  refreshable-duration: 604800  # 7 ngày

vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:3000/payment/return}"
  tmn-code: "OCP5JSX3"
  secret-key: "VYO09O0AQKQY0XFLKAVTKLDUM7CZ1TB8"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
