server:
  port: 8080
  servlet:
    context-path: /api/v1

dropbox:
  access:
    token: sl.u.AFtoqBjxIjRgljl56-PzxixdPrqF5KvV1etIxZ229FRYMoEjzwARsE7gBjxjXtyBLyxMz5tVNiZCrUiA33U3OYvh7o4OpjrX8pTH7gYaN3nFN5KS6udP_-vTVGds8EnDZZ_RWNZkQozW_7qxtdaWsZ5Ez40JewqNsWyw98ok9VpaPDEkUE_NGgvocwtPNDUR7aeO-rIbd9tUI77QYvvaM48U7G1T1Fe86uM04uUhmzsE8m9RRZyv52L-MwsdRiwxRftSfvvsspAyAVeYK9UcjBnipeXODcEFkQ2MBq_KZsViviEOdjKtNhyXddlHXBCLOYokaOY-ji-BtdBT_LFICMgSmSF8_S8ZKm3nL76qUEkHE9nTZjAPs1I4u37fjgTULbKg7OEetcJTfQPHOoggwVPQclJsobh6I96gQrl-T-CNaA-8HemGUb-T7HUbnopSZ-A79o2CwUtHgYgg2CeHOzH6YvDJmvJ8h5w5BiYPfQ60p39M1isHQgiFEN3iao5js9Wo-2B5Au1ywOef_bu4mV1yxrHi-ZPBTXwIbc3mZ3WkPSczAj_IzXrXiua3P6GjIqBe8pHC0e_I_9BFHS1krpfu0UgLjsvGXOG48y5Es_LeRGnvU2vGK4oUhllrTxntM1G01aTcfJ8QqfuSv6H9P6yWOn2QH4zjuXU7J6WAcD81v_eqLYnJVTn6T0lmu9cXGV30kZ2bQoeo4nO7idf8tT7ThQ8LmNTIZDVW_JW0BZxpVGwndPEjpDpL9390UJj63jpOj_gr_T6oy-RDGkd7Jv6IglGKZiOTVv5MyfVe420_kx3xudDVaCg2S7z0ErsaOQIlZH9ule2vSuxHhOHQXyRqWtgBpCddKhscCAm2JNrfc2QsuetrO0VLhq2KDXjEAcU5E5lsUxCsZRzHoTePYpRvRBZI8IXzJZLxuhp3NkLnKqQurdmkgF1ofnN6OduC-lMeYWGngSjGLFeqaS8wsPFkr32_-l8GqXXWxjcQgCoRLKv2O3jFEYi4vr_5FinwDM2nQpN8PwF77cFHJPgrjaA2f9cSB8P92kKoCBmj4AmuzOqy6nkKyTzAHsCAxu5Z8iLODmIWMtjAox-FEY8FzTSUnb-gzqC0WncbnIyiMWrTDOcihsmirv0Rnc-6VSAVqWoQiOukE7RRwdFCY-PSXEewEICxnv_9X9Uw-Imke1uz9tPEt0SfF9R2ynIWxdUVFd0H06KkGy-CFSYzEJpiKOI2JLmdVckpyTf0Gtd2Hy48O13zbAIcpv-Q6gJyGqbKY6XOW7vZv0Ka_-awBJ_fI5YQJQaELDTERTV6wTXnOBYRmAu8mfZnB3HEBLy7JwtLYa92TWmgy4FHuIH63Tmf9Bo1wYVJz5SOP8MEGWWLgPR6nZnkehyPsHMSdlFkY6faEWyCtvF_2pPUfvDu1RKi2BZrVjUpltwoyH4bJdUxnwAafQ


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/imageai"
    username: root
    password: "123456"

  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
